# Cloudflare Pages配置

# 项目基本信息
name = "aitolife"

# 构建和输出配置
[build]
command = "npm run build"
output_directory = "out"

# 环境变量配置
[build.environment]
NODE_VERSION = "18"

# 路由配置，用于处理SPA应用的客户端路由
[[routes]]
pattern = "/*"
script = "/404.html"
status = 404

# 浏览器TTL配置
[site.html_options]
worker_name = "aitolife-worker" 