# Cloudflare Pages配置

# 项目基本信息
name = "aitolife"
compatibility_date = "2023-06-15"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages 输出目录配置
pages_build_output_dir = ".vercel/output/static"

# 确保启用nodejs_compat标志
node_compat = true

# 构建和输出配置
[build]
command = "npm run build"
output_directory = "out"

# 环境变量配置
[env.production]
NODE_ENV = "production"

[env.preview]
NODE_ENV = "development"

# 路由配置，用于处理SPA应用的客户端路由
[[routes]]
pattern = "/*"
script = "/404.html"
status = 404

# 浏览器TTL配置
[site.html_options]
worker_name = "aitolife-worker" 